import type { Metadata } from "next";
import { displayFont, textFont } from "@/src/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${textFont.variable} ${displayFont.variable} h-full antialiased`}
      // The admin theme script may add a `dark` class before hydration.
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
